// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dubzwbfqlwhkpmpuejsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Ynp3YmZxbHdoa3BtcHVlanN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MTYwMjUsImV4cCI6MjA5MDE5MjAyNX0.XxzInie-IfWqyLiegkZl5zD3jx9w7F76mugjrIg53sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});